### ISSUE TITLE
EEPROM erased even if checkbox is not ticked- PIC18F27Q10 and PIC18F27K40

### ISSUE THREAD

**Issue by bernardlj** [Anobium/PICKitPlus#15]
I am using the Pickit 3 with the PicKit plus software to flash PIC models 18F27Q10 and 18F27K40, amongst others.
Application version 6.61.0.68
Device File Version: 2.63.221.3
OS Firmware Version: 2.00.05

When a PIC is flashed, its EEPROM is also cleared, even if the checkbox 'EEPROM Data' is not ticked in the GUI. 

Some firmware uses the EEPROM extensively and as a user, I do not want to recreate the correct EEPROM settings after a rewrite.

**Comment by Anobium** [comment]
This is resolve on 6.61.0.69 or greater of the application.

**Comment by Anobium** [comment]
I have sent the new version through to you.  Please check the new version.

**Comment by Anobium** [comment]
Use 6.61.0.69 or greater.

**Comment by bernardlj** [comment]
Thank you very much for the near-instant reply.
Thanks for the update, my issue has been resolved - well done!!!

**Comment by Anobium** [comment]
Excellent to hear!
