### ISSUE TITLE
add pic18f47q84

### ISSUE THREAD

**Issue by Aleksey-748** [Anobium/PICKitPlus#17]
Hello, is it possible to add pic18f47q84 in programmable microcontroller support.

**Comment by Anobium** [comment]
I am adding at the moment.

Please email me using your PICKITPlus contact info. I can share where I am.

**Comment by Anobium** [comment]
.

**Comment by Aleksey-748** [comment]
> Пожалуйста, напишите мне, используя вашу контактную информацию PICKITPlus. Я могу рассказать, где я нахожусь.

do you need an email address? my port.al2011 AT yandex.ru, just downloaded the software under pickit3

**Comment by Anobium** [comment]
We provide the new test database to registered users of the PICKitPlus software - this ensures it is tested.

Aleksey-748 are you a registered user ?

**Comment by Aleksey-748** [comment]
At the moment I am using the database in conjunction with the PICKIT3 software, I just did not find where and how to get by PICKIT3, I will be grateful for a hint.

**Comment by Anobium** [comment]
OK. See www.pickitplus.co.uk

None of the new chips work with the old Microchip PICKIT3 software.  An update is required.

**Comment by Aleksey-748** [comment]
Yes, I know, but the new programmer is quite expensive. Now I will try to register.

**Comment by Anobium** [comment]
? PICKitPlus is just software not a programmer.  Confused here.

**Comment by Aleksey-748** [comment]
Yes, everything is correct, I'm talking about PICKIT4. Looked at https://pickitplus.co.uk/Typesetter/ but there is no registration form?

**Comment by Anobium** [comment]
I thought for a moment that https://pickitplus.co.uk/Typesetter/ has been hacked.  :-)

Our software is licensed.  To obtain a license you need to get via PayPal - this project needs funds and we get nothing from Microchip to help.

**Comment by Aleksey-748** [comment]
It is clear, then the purchase is postponed until I persuade my parents.

**Comment by Anobium** [comment]
I understand the challenge.
The lowest cost option is here:  https://www.paypal.com/webapps/shoppingcart?mfid=1640950801122_f220778185895&flowlogging_id=f220778185895#/checkout/shoppingCart

:-)

**Comment by Aleksey-748** [comment]
Thank you.
