### ISSUE TITLE
Can these device dat files be used with official Pickit2 / 3 GUI applications?

### ISSUE THREAD

**Issue by snake-4** [Anobium/PICKitPlus#2]
I tried and it seems like new devices gets added to list, repository description claims these database files are for "Pickit Plus". Would they work if I try to flash a chip with these using official app?

**Comment by Anobium** [comment]
Some of the updates may work, any newer devices (that require the new communication protocol ) will not.

There is a way of telling. Look at the list of part. If the type has MSB in the type string then the part will not work with the old software. 

Hope this helps.

**Comment by snake-4** [comment]
Also, does Pickit Plus implement this new communication protocol and does it work on mplab mode of pickit 3 or only normal mode?

**Comment by Anobium** [comment]
Yes, PICKitPlus does implement the new communications protocol to support the newer parts.
PICKitPlus works in normal mode (not Mplab mode). We have kept the original firmware to ensure the software works with the widest range of PICKit2 and PICKit3 programmers ( Microchip, OEM and clones)
