### ISSUE TITLE
Fail verify configuration on PIC18F14K50

### ISSUE THREAD

**Issue by dginlon** [Anobium/PICKitPlus#3]
Fail verify configuration on PIC18F14K50

**No FAULT FOUND**

**Comment by Anobium** [comment]
I need more information..
What version of the GUI software?  Use Help/About to obtain this information.
What version of the parts database?

**Comment by dginlon** [comment]
PICkit2V2 V2.61.01
PK2DeviceFile.dat 1.63.194

**Comment by dginlon** [comment]
I have old one is good to program PIC18F14K50
https://www.dropbox.com/s/h5of7s0z7aftrrc/PK2DeviceFile.dat?dl=0
For your reference

**Comment by dginlon** [comment]
I have old one is ok to program PIC18F14K50 
https://www.dropbox.com/s/x0c6f5fpfpcli9i/PK2DeviceFile.dat?dl=0
for ur reference.

**Comment by Anobium** [comment]
I am confused.   You are using the old original Microchip GUI software with the latest database - correct?
Are you saying that that an old parts database worked with the old original Microchip software?
Please clarify - I do not understand the issue yet.


We test against PICKitPlus not the original Microchip software.   See http://www.pickitplus.co.uk/

**Comment by Anobium** [comment]
Is this resolved?  

I have reviewed the DAT files and I cannot see any differences.

**Comment by Anobium** [comment]
I do not think this was an issue.  As we have tested  K50 and no fault found,

**Comment by Anobium** [comment]
I do not think this was an issue.  As we have tested  K50 and no fault found,
