### ISSUE TITLE
Suggestions for HAF/SAF Data functional improvement  

### ISSUE THREAD

**Issue by dginlon** [Anobium/PICKitPlus#4]
My PICkit Plus   V4.61.0.45 

I'm amazing is has  HAF/SAF Data  backup function ,
But it cause me some inconvenience.
1. it can remember enable stat when next time use.
2.  The HEF/SAF Data region Length can be assign  over part spec.

**Comment by Anobium** [comment]
Great to get feedback.

1. We have included tbis functionality in PICKitPlus Autowatch.  The decision was to move this functionality to our new software.

2. Is this an issue? Do you mean you can select more HEFSAF than there really is? If so, which part?

**Comment by dginlon** [comment]
Thank for reply
if part has HEFSAF feature , this part can be as HEF operated on non-HEF region ,
Microchip will not guarantee .

**Comment by Anobium** [comment]
Ok. This could be included in the PICKitPlus Gang Programmer. 

Let me investigate the impact and get you the practicality and timeline.

**Comment by Anobium** [comment]
Closef

**Comment by Anobium** [comment]
Closed
