### ISSUE TITLE
I can't connect to PIC16F15323

### ISSUE THREAD

**Issue by Tiberiu62** [Anobium/PICKitPlus#5]
When I try to connect to PIC16F15323 I get the message (PICkit2):
**Device: Unsuported part (ID = 00C3)**

**Comment by Anobium** [comment]
Hi.

What version of the GUI software are you using? Look in help/about.

**Comment by Tiberiu62** [comment]
Application Version 2.61.00
Device File Version 2.63.216

**Comment by Anobium** [comment]
You have the old PICkit GUI software.

We publish the parts database for PICKitPlus which is compatible with the old software but to make the new chips work you need to change the software to PICKitPlus, or, change your programmer. There are many other programming options but our software supports the PICKit2 and PICKit3 programmers.

For PICKITPlus see www.pickitplus.co.uk

**Comment by Tiberiu62** [comment]
Thank you
