### ISSUE TITLE
PIC16F19156

### ISSUE THREAD

**Issue by robi772** [Anobium/PICKitPlus#6]
Hi, 
My PIC16F19156 device id is 0643 with the normal programs.

**Comment by Anobium** [comment]
Sorry.  I am not sure what the question is.

Can you clarify please?

**Comment by Anobium** [comment]
I am thinking you are using the old Pickit software with the new .dat.

I recommend you upgrade to the Flex PICKitPlus software. Same programmer, new software that works with your 16f19156 chip.  See www.pickitplus.co.uk for the Flex software.

Your existing software cannot support the 16f19156 chip. You will need change the software.  Another option is MPLAB-X with a new Pickit programmer.

Evan

**Comment by Anobium** [comment]
My thinking is correct.  You need to upgrade to the Flex PICKitPlus software. Same programmer, new software that works with your 16f19156 chip. See www.pickitplus.co.uk for the Flex software, or, change you programmer solution.

The image shows two GUIs.  The left is the old Microchip software and the right is PICKitPlus software.  They are both using the same parts database.  And, as you can see the old Microchip software = 0x0643 and the PICKitPlus software = 0x3098 which is correct.

![image](https://user-images.githubusercontent.com/17933379/93976687-3f19ab00-fd71-11ea-86d6-e00592321c14.png)


Also note:  PICKitPlus software has support for HEF/SAF and a lot more functionality.

**Comment by Anobium** [comment]
Upgrade to PICKitPlus or change the programming solution.

Using the new parts database is great for getting the widest support for legacy parts, but, for newer parts PICKitPlus is required.
